[package]
edition.workspace = true
license.workspace = true
name = "lemurclaw-utils-output-truncation"
version.workspace = true

[lints]
workspace = true

[dependencies]
lemurclaw-protocol = { workspace = true }
lemurclaw-utils-string = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }

[lib]
doctest = false
