
[package]
edition.workspace = true
license.workspace = true
name = "lemurclaw-utils-plugins"
version.workspace = true

[lib]
doctest = false
name = "lemurclaw_utils_plugins"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
lemurclaw-exec-server = { workspace = true }
lemurclaw-exec-server-protocol = { workspace = true }
lemurclaw-utils-absolute-path = { workspace = true }
lemurclaw-utils-path-uri = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
