[package]
edition.workspace = true
license.workspace = true
name = "lemurclaw-analytics"
version.workspace = true

[lib]
doctest = false
name = "lemurclaw_analytics"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
lemurclaw-app-server-protocol = { workspace = true }
lemurclaw-git-utils = { workspace = true }
lemurclaw-login = { workspace = true }
lemurclaw-model-provider = { workspace = true }
lemurclaw-plugin = { workspace = true }
lemurclaw-protocol = { workspace = true }
lemurclaw-state = { workspace = true }
os_info = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha1 = { workspace = true }
tokio = { workspace = true, features = [
    "macros",
    "rt-multi-thread",
] }
tracing = { workspace = true, features = ["log"] }

[dev-dependencies]
lemurclaw-utils-absolute-path = { workspace = true }
pretty_assertions = { workspace = true }
