// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LemurclawErrorInfo } from "./LemurclawErrorInfo";

export type TurnError = { message: string, codexErrorInfo: LemurclawErrorInfo | null, additionalDetails: string | null, };
