[package]
name = "lemurclaw-install-context"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "lemurclaw_install_context"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
lemurclaw-utils-absolute-path = { workspace = true }
lemurclaw-utils-home-dir = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
