[package]
edition.workspace = true
license.workspace = true
name = "lemurclaw-code-mode"
version.workspace = true

[lib]
doctest = false
name = "lemurclaw_code_mode"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
lemurclaw-code-mode-protocol = { workspace = true }
lemurclaw-http-client = { workspace = true }
