[package]
edition.workspace = true
license.workspace = true
name = "lemurclaw-models-manager"
version.workspace = true

[lib]
doctest = false
name = "lemurclaw_models_manager"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
chrono = { workspace = true, features = ["serde"] }
lemurclaw-collaboration-mode-templates = { workspace = true }
lemurclaw-http-client = { workspace = true }
lemurclaw-login = { workspace = true }
lemurclaw-otel = { workspace = true }
lemurclaw-protocol = { workspace = true }
lemurclaw-utils-output-truncation = { workspace = true }
lemurclaw-utils-template = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["fs", "sync", "time"] }
tracing = { workspace = true, features = ["log"] }

[dev-dependencies]
pretty_assertions = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
