[package]
edition.workspace = true
license.workspace = true
name = "lemurclaw-mcp"
version.workspace = true

[lib]
name = "lemurclaw_mcp"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
arc-swap = { workspace = true }
async-channel = { workspace = true }
lemurclaw-async-utils = { workspace = true }
lemurclaw-api = { workspace = true }
lemurclaw-config = { workspace = true }
lemurclaw-connectors = { workspace = true }
lemurclaw-exec-server = { workspace = true }
lemurclaw-login = { workspace = true }
lemurclaw-model-provider = { workspace = true }
lemurclaw-otel = { workspace = true }
lemurclaw-protocol = { workspace = true }
lemurclaw-rmcp-client = { workspace = true }
lemurclaw-utils-path-uri = { workspace = true }
lemurclaw-utils-plugins = { workspace = true }
futures = { workspace = true }
lru = { workspace = true }
regex-lite = { workspace = true }
rmcp = { workspace = true, default-features = false, features = ["base64", "macros", "schemars", "server"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha1 = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["io-util", "macros", "rt-multi-thread"] }
tokio-util = { workspace = true, features = ["rt"] }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
lemurclaw-plugin = { workspace = true }
pretty_assertions = { workspace = true }
rmcp = { workspace = true, default-features = false, features = ["base64", "macros", "schemars", "server"] }
tempfile = { workspace = true }
